# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version  (ie 5.5.0)'
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Update version in pom.xml (Release only)
      run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
    - name: Create Release Branch
      run: |
        git checkout -b release/v${{ github.event.inputs.version }}
        git config user.name github-actions
        git config user.email noreply@github.com
        git add *pom.xml
        git commit -m "Release ${{ github.event.inputs.version }}"
        git push origin release/v${{ github.event.inputs.version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#       GITHUB_TOKEN: ${{ github.token }}
    - run: mkdir staging
    - run: cp status-api/target/*.jar staging
    - run: cp spring-status/target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
       name: Package
       path: staging
